<?php

namespace App\Features\AccessReviews\Repositories;

use App\Features\AccessReviews\Models\AccessReview;
use Carbon\CarbonInterface;
use Illuminate\Support\Collection;

// Every database read and write for access review reports
class AccessReviewRepository
{
    /** The newest reports, with who generated and reviewed them. */
    public function latest(int $limit = 50): Collection
    {
        return AccessReview::with(['reviewer', 'generator'])->latest('id')->limit($limit)->get();
    }

    public function create(array $attributes): AccessReview
    {
        return AccessReview::create($attributes);
    }

    /** Deletes the reports generated by hand for exactly this period; returns their ids. */
    public function deleteManualFor(string $type, CarbonInterface $start, CarbonInterface $end): Collection
    {
        $ids = AccessReview::where('scheduled', false)
            ->where('period_type', $type)
            ->whereDate('period_start', $start->toDateString())
            ->whereDate('period_end', $end->toDateString())
            ->pluck('id');
        AccessReview::whereKey($ids)->delete();

        return $ids;
    }

    /** Whether the schedule already made a report for this period. */
    public function scheduledExists(string $type, CarbonInterface $start, CarbonInterface $end): bool
    {
        return AccessReview::where('scheduled', true)
            ->where('period_type', $type)
            ->whereDate('period_start', $start->toDateString())
            ->whereDate('period_end', $end->toDateString())
            ->exists();
    }

    public function delete(AccessReview $review): void
    {
        $review->delete();
    }

    public function withPeople(AccessReview $review): AccessReview
    {
        return $review->load(['reviewer', 'generator']);
    }
}
