import { useEffect, useState } from 'react'
import { createPortal } from 'react-dom'
import { ClipboardCheck, FileDown, Power, X } from 'lucide-react'
import { useEscapeKey } from '../../hooks'
import { PERIOD_TYPES, REVIEW_FLAGS, downloadAccessReviewCsv, fetchAccessReview, formatPeriod, markAccessReviewed } from './accessReviews'

// One access review: who has access, their last sign-in, and what needs attention
export default function AccessReviewModal({ reviewId, accounts, onClose, onReviewed, onDeactivate }) {
  const [review, setReview] = useState(null)
  const [error, setError] = useState(null)
  const [onlyFlagged, setOnlyFlagged] = useState(true)
  const [note, setNote] = useState('')
  const [isSaving, setIsSaving] = useState(false)

  useEscapeKey(onClose)

  useEffect(() => {
    let ignore = false
    fetchAccessReview(reviewId)
      .then((data) => {
        if (ignore) return
        setReview(data)
        setNote(data.reviewNote || '')
        setOnlyFlagged(data.summary.needsAttention > 0)
      })
      .catch((e) => !ignore && setError(e.message))
    return () => {
      ignore = true
    }
  }, [reviewId])

  const markReviewed = async () => {
    setIsSaving(true)
    try {
      const { review: updated } = await markAccessReviewed(review.id, note.trim() || null)
      setReview((prev) => ({ ...prev, ...updated, rows: prev.rows }))
      onReviewed(updated)
    } catch (e) {
      setError(e.message)
    } finally {
      setIsSaving(false)
    }
  }

  // The report is a snapshot; this is the account as it is now (it may have been changed since)
  const liveAccount = (row) => accounts.find((a) => a.id === row.userId)
  const rows = review ? review.rows.filter((r) => !onlyFlagged || r.flags.length) : []
  const s = review?.summary

  // Rendered at the top of the page so it centres on the screen, not inside the page card
  return createPortal(
    <div className="modal-overlay" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="access-review-title" style={{ maxWidth: '1100px' }}>
        <div className="modal-header">
          <div className="modal-title-wrap">
            <div className="stat-icon-wrapper cyan">
              <ClipboardCheck size={20} />
            </div>
            <div>
              <h2 id="access-review-title">{review ? `${PERIOD_TYPES[review.periodType]?.label || ''} Access Review · ${formatPeriod(review)}` : 'Access Review'}</h2>
              <p className="page-desc">
                {review
                  ? `${review.scheduled ? 'Scheduled report' : `Generated by ${review.generatedBy || 'the Owner'}`} on ${new Date(review.generatedAt).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}. Dormant = no sign-in for ${s.dormantDays}+ days.`
                  : 'Loading…'}
              </p>
            </div>
          </div>
          <button type="button" className="modal-close-btn" onClick={onClose} aria-label="Close">
            <X size={18} />
          </button>
        </div>

        <div className="modal-form">
          {error && <span className="error-msg">{error}</span>}

          {review && (
            <>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                <span className="stat-chip neutral">{s.totalUsers} users</span>
                {Object.entries(s.byRole).filter(([, n]) => n).map(([role, n]) => (
                  <span key={role} className="stat-chip neutral">{role}: {n}</span>
                ))}
                <span className={`stat-chip ${s.dormant ? 'negative' : 'positive'}`}>Dormant: {s.dormant}</span>
                <span className={`stat-chip ${s.roleChanged ? 'negative' : 'positive'}`}>Role changes: {s.roleChanged}</span>
                <span className={`stat-chip ${s.staleInvitations ? 'negative' : 'positive'}`}>Invitations not accepted: {s.staleInvitations}</span>
                <span className="stat-chip neutral">Deactivated on file: {s.deactivated}</span>
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', gap: '1rem', flexWrap: 'wrap' }}>
                <label className="inline-check">
                  <input type="checkbox" checked={onlyFlagged} onChange={(e) => setOnlyFlagged(e.target.checked)} />
                  Show only accounts that need attention ({s.needsAttention})
                </label>
                <button type="button" className="secondary-action-btn" onClick={() => downloadAccessReviewCsv(review)}>
                  <FileDown size={16} /> Download CSV
                </button>
              </div>

              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Staff member</th>
                      <th>Role</th>
                      <th>Branch</th>
                      <th>Status</th>
                      <th>Last sign-in</th>
                      <th>Flags</th>
                      <th>Action</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((r) => {
                      const live = liveAccount(r)
                      const canDeactivate = live && live.status === 'Active' && live.role !== 'owner' && (r.flags.includes('dormant') || r.flags.includes('role_changed'))
                      return (
                        <tr key={r.userId}>
                          <td>
                            <div className="fw-600">{r.fullName}</div>
                            <div className="field-hint">{r.email}</div>
                          </td>
                          <td className="nowrap">
                            {r.roleLabel}
                            {r.roleChanges.map((c) => (
                              <div key={c.at} className="field-hint">{c.from} → {c.to} on {c.at.slice(0, 10)}</div>
                            ))}
                          </td>
                          <td className="nowrap">{r.branchName || '—'}</td>
                          <td className="nowrap">
                            {r.status}
                            {live && live.status !== r.status && <div className="field-hint">Now {live.status}</div>}
                            {!live && <div className="field-hint">Since deleted</div>}
                          </td>
                          <td className="nowrap">
                            {r.lastLoginAt ? new Date(r.lastLoginAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }) : 'Never'}
                            {r.daysSinceLogin !== null && <div className="field-hint">{r.daysSinceLogin} days ago</div>}
                          </td>
                          <td>
                            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.3rem' }}>
                              {r.flags.length
                                ? r.flags.map((f) => (
                                  <span key={f} className={`status-tag ${REVIEW_FLAGS[f]?.tone || 'inactive'}`} title={REVIEW_FLAGS[f]?.hint}>
                                    {REVIEW_FLAGS[f]?.label || f}
                                  </span>
                                ))
                                : <span className="not-set">OK</span>}
                            </div>
                          </td>
                          <td>
                            {canDeactivate
                              ? (
                                <button type="button" className="link-btn danger-link" onClick={() => onDeactivate(live)}>
                                  <Power size={14} /> Deactivate
                                </button>
                              )
                              : <span className="not-set">—</span>}
                          </td>
                        </tr>
                      )
                    })}
                    {rows.length === 0 && (
                      <tr>
                        <td colSpan={7} style={{ color: 'var(--text-dim)', textAlign: 'center', padding: '2rem' }}>
                          Nothing needs attention in this period.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>

              {review.reviewedAt ? (
                <p className="page-desc">
                  Reviewed by {review.reviewedBy} on {new Date(review.reviewedAt).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}
                  {review.reviewNote ? `: “${review.reviewNote}”` : '.'}
                </p>
              ) : (
                <>
                  <div className="form-group">
                    <textarea
                      id="review-note"
                      aria-label="Review note (optional)"
                      className="input-field"
                      rows={3}
                      placeholder="e.g. Deactivated 2 dormant accounts; confirmed the Pharmacist promotion is needed."
                      value={note}
                      onChange={(e) => setNote(e.target.value)}
                      style={{ resize: 'vertical', minHeight: '4.5rem', paddingTop: '0.6rem' }}
                    />
                  </div>
                  <div className="modal-actions">
                    <button type="button" className="secondary-action-btn" onClick={onClose}>Close</button>
                    <button type="button" className="primary-action-btn" onClick={markReviewed} disabled={isSaving}>
                      <ClipboardCheck size={16} /> {isSaving ? 'Saving…' : 'Mark as reviewed'}
                    </button>
                  </div>
                </>
              )}
            </>
          )}
        </div>
      </div>
    </div>,
    document.body
  )
}
