import { useEffect, useState } from 'react'
import { useSelector } from 'react-redux'
import { createPortal } from 'react-dom'
import { ClipboardCheck, FileText, X } from 'lucide-react'
import { useEscapeKey } from '../../../hooks'
import { fetchAccessReview } from '../api/accessReviewsApi'
import { PERIOD_TYPES } from '../model/accessReview'
import { exportAccessReviewPdf, formatPeriod, lastSignInText, localDate } from '../services/accessReviews'
import { selectSettings } from '../../policy/store/settingsSlice'

// One access review: who has access, their role and last sign-in, with Export PDF
export default function AccessReviewModal({ reviewId, accounts, onClose }) {
  const [review, setReview] = useState(null)
  const [error, setError] = useState(null)
  const [isExporting, setIsExporting] = useState(false)
  const { pharmacyName } = useSelector(selectSettings)

  useEscapeKey(onClose)

  useEffect(() => {
    let ignore = false
    fetchAccessReview(reviewId)
      .then((data) => {
        if (ignore) return
        setReview(data)
      })
      .catch((e) => !ignore && setError(e.message))
    return () => {
      ignore = true
    }
  }, [reviewId])

  const exportPdf = async () => {
    setIsExporting(true)
    try {
      await exportAccessReviewPdf(review, pharmacyName)
    } catch (e) {
      setError(`The PDF couldn't be created: ${e.message}`)
    } finally {
      setIsExporting(false)
    }
  }

  // The report is a snapshot; this is the account as it is now (it may have been changed since)
  const liveAccount = (row) => accounts.find((a) => a.id === row.userId)
  const rows = review ? review.rows : []
  const s = review?.summary

  // Rendered at the top of the page so it centres on the screen, not inside the page card
  return createPortal(
    <div className="modal-overlay" onMouseDown={(e) => e.target === e.currentTarget && onClose()}>
      <div className="modal-card" role="dialog" aria-modal="true" aria-labelledby="access-review-title" style={{ maxWidth: '1100px' }}>
        <div className="modal-header">
          <div className="modal-title-wrap">
            <div className="stat-icon-wrapper cyan">
              <ClipboardCheck size={20} />
            </div>
            <div>
              <h2 id="access-review-title">{review ? `${PERIOD_TYPES[review.periodType]?.label || ''} Access Review · ${formatPeriod(review)}` : 'Access Review'}</h2>
              <p className="page-desc">
                {review
                  ? `${review.scheduled ? 'Scheduled report' : `Generated by ${review.generatedBy || 'the Owner'}`} on ${new Date(review.generatedAt).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}. Dormant = no sign-in for ${s.dormantDays}+ days.`
                  : 'Loading…'}
              </p>
            </div>
          </div>
          <button type="button" className="modal-close-btn" onClick={onClose} aria-label="Close">
            <X size={18} />
          </button>
        </div>

        <div className="modal-form">
          {error && <span className="error-msg">{error}</span>}

          {review && (
            <>
              <div style={{ display: 'flex', flexWrap: 'wrap', gap: '0.5rem' }}>
                <span className="stat-chip neutral">{s.totalUsers} users</span>
                {Object.entries(s.byRole).filter(([, n]) => n).map(([role, n]) => (
                  <span key={role} className="stat-chip neutral">{role}: {n}</span>
                ))}
                <span className={`stat-chip ${s.dormant ? 'negative' : 'positive'}`}>Dormant: {s.dormant}</span>
                <span className={`stat-chip ${s.roleChanged ? 'negative' : 'positive'}`}>Role changes: {s.roleChanged}</span>
                <span className={`stat-chip ${s.staleInvitations ? 'negative' : 'positive'}`}>Invitations not accepted: {s.staleInvitations}</span>
                <span className="stat-chip neutral">Deactivated on file: {s.deactivated}</span>
              </div>

              <div style={{ display: 'flex', justifyContent: 'flex-end' }}>
                <button type="button" className="secondary-action-btn" onClick={exportPdf} disabled={isExporting}>
                  <FileText size={16} /> {isExporting ? 'Preparing PDF…' : 'Export PDF'}
                </button>
              </div>

              <div className="table-responsive">
                <table className="data-table">
                  <thead>
                    <tr>
                      <th>Staff member</th>
                      <th>Role</th>
                      <th>Branch</th>
                      <th>Status</th>
                      <th>Last sign-in</th>
                    </tr>
                  </thead>
                  <tbody>
                    {rows.map((r) => {
                      const live = liveAccount(r)
                      return (
                        <tr key={r.userId}>
                          <td>
                            <div className="fw-600">{r.fullName}</div>
                            <div className="field-hint">{r.email}</div>
                          </td>
                          <td className="nowrap">
                            {r.roleLabel}
                            {r.roleChanges.map((c) => (
                              <div key={c.at} className="field-hint">{c.from} → {c.to} on {localDate(c.at)}</div>
                            ))}
                          </td>
                          <td className="nowrap">{r.branchName || '—'}</td>
                          <td className="nowrap">
                            {r.status}
                            {live && live.status !== r.status && <div className="field-hint">Now {live.status}</div>}
                            {!live && <div className="field-hint">Since deleted</div>}
                          </td>
                          <td className="nowrap">
                            {lastSignInText(r, (iso) => new Date(iso).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }))}
                            {r.daysSinceLogin !== null && <div className="field-hint">{r.daysSinceLogin} days before {review.periodEnd}</div>}
                          </td>
                        </tr>
                      )
                    })}
                    {rows.length === 0 && (
                      <tr>
                        <td colSpan={5} style={{ color: 'var(--text-dim)', textAlign: 'center', padding: '2rem' }}>
                          No accounts in this period.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </>
          )}
        </div>
      </div>
    </div>,
    document.body
  )
}
