// Colour class for every status label shown with <StatusTag>
export const STATUS_TONE = {
  'In Stock': 'in-stock',
  'Low Stock': 'low-stock',
  'Out of Stock': 'out-of-stock',
  'Paid': 'in-stock',
  'Cleared': 'in-stock',
  'Received': 'in-stock',
  'Active': 'in-stock',
  'Completed': 'in-stock',
  'Refunded': 'out-of-stock',
  'Partially Refunded': 'low-stock',
  'Restocked': 'in-stock',
  'Written Off': 'out-of-stock',
  'Idle': 'low-stock',
  'Ended': 'inactive',
  'Returned': 'out-of-stock',
  'Partially Returned': 'low-stock',
  'Inactive': 'inactive',
  'Pending': 'low-stock',
  'Approved': 'in-stock',
  'Rejected': 'out-of-stock',
  'Replaced': 'in-stock',
  'Partially Replaced': 'low-stock',
  'Credit Owed': 'low-stock',
  'No Credit': 'inactive',
  'Failed': 'out-of-stock'
}
